"use strict";
let places = ['Makkah', 'Saudia Arab', 'Dubai', 'Italy', 'England'];
console.log('orignal; ' + places);
console.log('copy ' + [...places].sort());
console.log('orignal; ' + places);
console.log('copy ' + [...places].sort().reverse());
console.log('copy ' + [...places].sort().reverse());
console.log('orignal; ' + places.sort());
console.log('orignal; ' + places.sort().reverse());
console.log('orignal; ' + places.sort());
